name: rss

on:
  schedule:
    - cron: 0 */8 * * *
  workflow_dispatch:
jobs:
  rss:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        wget -q https://github.com/mawaya/rclone/releases/download/fclone-v0.4.1/fclone-v0.4.1-linux-amd64.zip
        unzip fclone-v0.4.1-linux-amd64.zip
        sudo mv fclone-v0.4.1-linux-amd64/fclone /usr/bin/fclone
        chmod +x /usr/bin/fclone
        sudo apt install unrar -y -q
        ip a
    - name: Inject Rclone config
      env:
        RSS_CONFIG: ${{ secrets.RSS_CONFIG }}
      run: |
        wget -q https://github.com/$GITHUB_REPOSITORY/raw/main/accounts.rar
        unrar -p'${{ secrets.RAR_PSWD }}' e accounts.rar ~/accounts/
        index=`ls -l ~/accounts |grep "^-"|wc -l`
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${RSS_CONFIG/1.json/$((RANDOM%$index+1)).json}
        EOF
    - name: gclone run
      run: |
          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          # 开始同步
          fclone copy ${{ secrets.RSS_PATH }}  --stats-log-level NOTICE -P --stats 30s --cache-chunk-total-size 30G --transfers=12 --drive-chunk-size 128M  --max-backlog 1000
          echo "DONE" 
